### ISSUE TITLE
Code blocks and activities checklist

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/oo#1]
@bocharsky-bw we need your help publishing the next course! For each chapter, we need to add code blocks and the activities. I'm "creating" the activities in text as I watch the final videos in this file: https://github.com/knpuniversity/oo/blob/master/knpu/episode3/_activities_notes.md. Basically, we need to convert those into the real activities.

I'll add more todos with more chapters as they're ready. If there's a better way for us to organize all of this, let's find it :).
- [x] `01-extends` code blocks
- [x] `01-extends` activities
- [x] `02-override` code blocks
- [x] `02-override` activities
- [x] `03-protected-visibility` code blocks
- [x] `03-protected-visibility` activities
- [x] `04-parent` code blocks
- [x] `04-parent` activities
- [x] `05-abstract-ship` code blocks
- [x] `05-abstract-ship` activities
- [x] `06-adding-abstract` code blocks
- [x] `06-adding-abstract` activities
- [x] `07-broken-ship` code blocks
- [x] `07-broken-ship` activities
- [x] `08-pdo-ship-storage` code blocks
- [x] `08-pdo-ship-storage` activities
- [x] `09-abstract-ship-loader` code blocks
- [x] `09-abstract-ship-loader` activities
- [x] `10-interfaces` code blocks
- [x] `10-interfaces` activities

**Comment by bocharsky-bw** [comment]
Phew... Whole episode 3 is done, finally! :)
